### PR TITLE
improve performance using map

### PR DESCRIPTION
**Pull request by snapsl**
exchanged list comprehensions with map

@mmotti Also thank you for this awsm script.

### CODE REVIEW

**Comment by mmotti** [comment]
Hey!

Thanks for your suggestions :-)

I am fairly new to Python so please feel free to correct me on any of the following questions / comments.
1. `set_gravity_domains.update(map(lambda x : x if (x and x[:1] != '#') else None, map(str.strip, fOpen)))`
Is there much performance increase to be gained from using map? Also, I don't think `map(str.strip, fOpen)` will work in the way I intend it to. If I understand correctly, this will only strip the start and end of the string as a whole, whereas I need to remove excess spaces from each individual line.

2. ` fWrite.write('\n'.join(sorted(set_gravity_domains)))`
I was playing around with this sort of thing before but with devices like Raspberry Pis, you have to be very careful with how much memory you are using; I had to re-write this script from Bash to Python for that very reason. I believe that this could potentially cause issues for people with large gravity lists (5M+), as generating a huge string in memory before writing it to a file will inevitably be more demanding than writing each element in a for loop.

**Comment by snapsl** [comment]
1. there is a slight performance increase. see the time measurements in the following thread.
https://stackoverflow.com/questions/1247486/list-comprehension-vs-map
also the map should be applied to every line as shown here:
`>>>map(str.lower, ["A","B","C"])` 
`['a', 'b', 'c']`

2. I had not considered memory issues. I don't know if this could get a problem with a large gravity.list.

I could revert the second part. The usage of map should be fine.

**Comment by mmotti** [comment]
Ah, I see... Map uses an iterator! I stand corrected.

I will take a proper look through this in the near future :-) Will update you soon

**Comment by mmotti** [comment]
The stackoverflow link seems to suggest that map is generally faster than list comprehension with the exception of when using a lambda function.

I have done a little testing and these were my results:
```
set_gravity_domains.update(x for x in (line.strip() for line in fOpen) if x and x[:1] != '#')
0:00:00.070852
0:00:00.079821
0:00:00.076224

set_gravity_domains.update(x for x in map(str.strip, fOpen) if x and x[:1] != '#')
0:00:00.077936
0:00:00.075048
0:00:00.076540


set_gravity_domains.update(map(lambda x : x if (x and x[:1] != '#') else None, map(str.strip, fOpen)))
0:00:00.068518
0:00:00.074957
0:00:00.086715
```

Although the map / lambda combo seemed to perform faster on a couple of occasions, I do prefer the readability of option two and the timing seems to stay pretty consistent.

Could we perhaps compromise with: 
`set_gravity_domains.update(x for x in map(str.strip, fOpen) if x and x[:1] != '#')` ?

I also think it would be an idea to revert back to the line-by-line writeout for the gravity.list (bearing in mind that this will be irrelevant anyway as soon as Pihole v5 is released)

If you are happy with this and happy to update the pull-request, I could merge it? Otherwise I can make the changes on my end :-)

**Comment by snapsl** [comment]
Done :)

**Pull request merged**
